name: first workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Print current directory
        run: |
          echo "Current directory before changing: $(pwd)"
          echo "Listing files:"
          ls -l

      - name: List .github/workflows directory
        run: |
            cd "../"
            cd "./LearnGitHubActions/.github/workflows/second-action.yml"
            echo "Current directory: $(pwd)"
