name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print start
        run: echo "Action starting"

      # - name: download base-proj3 jar
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: application-jar
      #     path: base-proj3/target
      
      - name: print downloaded artifact
        run: ls base-proj3/target

      - name: copy artifact to project
        run: cp base-proj3/target/base-proj3-1.0-SNAPSHOT.jar base-proj1/target/base-proj1.jar

      - name: print end
        run: echo "Action ended"
