name: first workflow
on: workflow_call
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:

      - name: Print current directory
        run: |
          echo "Current directory before changing: $(pwd)"
          echo "Listing files:"
          ls -r