name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print start
        run: echo "Action starting"

      - name: Restore build artifact
        uses: actions/cache@v4
        with:
          path: base-proj3/target/
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: ${{ runner.os }}-base-proj3-jar

      - name: List retrieved artifact
        run: ls -l

      - name: print end
        run: echo "Action ended"
