name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print start
        run: echo "Action starting"

      - name: print end
        run: echo "Action ended"

      - name: Print current directory
        run: |
          echo "Current directory before changing: $(pwd)"
          echo "Listing files:"
          ls -l

      - name: List .github/workflows directory
        working-directory: .github/workflows
        run: |
            cd "../../../"
            echo "Current directory: $(pwd)"
            ls -la