name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print start
        run: echo "Action starting"

      - name: print context
        run: echo "'context:' ${{ github.context }}"

      - name: print end
        run: echo "Action ended"
