name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print start
        run: echo "Action starting"

      - name: Restore build artifact
        uses: actions/cache@v3
        with:
          path: base-proj3/target/
          key: base-proj3-jar-${{ github.ref_name }}
          restore-keys: base-proj3-jar
          save-always: true

      - name: List retrieved artifact
        run: ls -l base-proj3/target

      - name: print end
        run: echo "Action ended"
