name: first workflow
on: workflow_call
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print start
        run: echo "Action starting"

      - name: print end
        run: echo "Action ended"
