name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print start
        run: echo "Action starting"

      - name: print end
        run: echo "Action ended"

      - name: Print current directory
        run: |
          echo "Current directory before changing: $(pwd)"
          echo "Listing files:"
          ls -l

      - name: List .github/workflows directory
        working-directory: .github/workflows
        run: |
          echo "Changing directory to .github/workflows"
          cd .github/workflows
          echo "Current directory after changing: $(pwd)"
          echo "Listing files in .github/workflows:"
          ls -l
