name: fourth-action
on:
  push:
    branches:
      - main
      - dev
env:
  MONGODB_DB_NAME: cluster-1
jobs:
  test:
    env:
      MONGODB_CLUSTER_ADDRESS: cluster-1.8ndbkwc.mongodb.net
      MONGODB_USERNAME: karchowdhurysubham
      MONGODB_PASSWORD: 5enH1XPMpVJYILe1
      PORT: 8080

    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        working-directory: base-proj4

      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
        working-directory: base-proj4

      - name: Run tests
        run: npm test
        working-directory: base-proj4

      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_DB_NAME: ${{ env.MONGODB_DB_NAME }}"
