name: second workflow
on:
  push:
    branches:
      - main # run action when push in main branch
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest # Os for GitHub vm
    steps:
        # Checkout the code. Respository path can be added
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Caching npm dependencies
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: dep-node-modules-${{ hashFiles('**/package-lock.json') }}

        # Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: base-Proj2

        # Run tests
      - name: Run tests
        run: npm test
        working-directory: base-Proj2

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: dep-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        working-directory: base-Proj2

      - name: Build code
        run: npm run build
        working-directory: base-Proj2
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: base-Proj2

  deploy_code:
    needs: build_code
    runs-on: ubuntu-latest
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files
      
      - name: Output contents
        run: ls
      
      - name: Deploy code
        run: echo "Deploying code..."