name: Test workflow
on:
  push:
    branches:
      - main # run action when push in main branch
jobs:
  test_code:
    runs-on: ubuntu-latest # Os for GitHub vm
    steps:
        # Checkout the code. Respository path can be added
      - name: Checkout code
        uses: actions/checkout@v4
      
        # Install required Runtime if not pre-installed
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

        # Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: base-Proj2

        # Run tests
      - name: Run tests
        run: npm test
        working-directory: base-Proj2
  
  build_code:
    needs: test_code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: base-Proj2

      - name: Build code
        run: npm run build
        working-directory: base-Proj2
