name: Test workflow
on:
  push:
    branches:
      - main # run action when push in main branch
jobs:
  deploy_code:
    runs-on: ubuntu-latest # Os for GitHub vm
    steps:

        # Checkout the code. Respository path can be added
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: base-Proj2
      
        # Install required Runtime if not pre-installed
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          check-latest: false
      
        # Install dependencies
      - name: Install dependencies
        run: |
          cd base-Proj2
          npm ci