name: second workflow
on:
  push:
    branches:
      - main # run action when push in main branch
  workflow_dispatch:
jobs:
  test_code:
    runs-on: ubuntu-latest # Os for GitHub vm
    steps:
        # Checkout the code. Respository path can be added
      - name: Checkout code
        uses: actions/checkout@v4
      
        # Install required Runtime if not pre-installed
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

        # Caching npm dependencies
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: dep-node-modules-${{ hashFiles('**/package-lock.json') }}

        # Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: base-Proj2

        # Run tests
      - name: Run tests
        run: npm test
        working-directory: base-Proj2
  
  build_code:
    needs: test_code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: dep-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        working-directory: base-Proj2

      - name: Build code
        run: npm run build
        working-directory: base-Proj2
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: base-Proj2/build

  deploy_code:
    needs: build_code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      
      - name: Deploy code
        run: echo "Deploying code..."