name: Test workflow
on:
  push:
    branches:
      - main # run action when push in main branch
jobs:
  deploy_code:
    runs-on: ubuntu-latest # Os for GitHub vm
    steps:

        # Checkout the code. Respository path can be added
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: baseProj2
      
        # Install required Runtime if not pre-installed
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          check-latest: false
      
        # Install dependencies
      - name: Install dependencies
        run: |
          if [ -f baseProj2/package-lock.json ]; then
           npm ci
          else
            npm install
          fi
        # working-directory: baseProj2
      
      #   # Run tests
      # - name: Run test
      #   run: npm test
      #   working-directory: baseProj2