name: third workflow
on:
  push:
    branches:
      - main # run action when push in main branch
  workflow_dispatch:
jobs:
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps to run as part of the job
    steps:
    # Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK 17 (you can change the version if needed)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    # Cache Maven dependencies to speed up build times
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    # Run Maven package and verify
    - name: Build with Maven
      run: mvn clean install

    # Optionally, you can add steps to run tests and more
    - name: Run tests
      run: mvn test