name: third workflow
on:
  push:
    branches:
      - main # run action when push in main branch
  workflow_dispatch:
    
jobs:
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps to run as part of the job
    steps:
    # Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up JDK 17 (you can change the version if needed)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: maven

    # Cache Maven dependencies to speed up build times
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: maven-cache-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
                ${{ runner.os }}-maven-

    # Run Maven package and verify
    - name: Build with Maven
      run: mvn clean install
      working-directory: base-proj3

    # Verify the contents of the target directory
    - name: List target directory
      run: ls -l base-proj3/target

    # Upload the JAR file to GitHub Actions artifacts   
    - name: Upload JAR file
      uses: actions/upload-artifact@v4
      with:
        name: base-proj3-jar
        path: base-proj3/target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Get build artifact
        uses: actions/download-artifact@v4
        with:
          name: base-proj3-jar

      - name: Output artifact
        run: ls

      - name: Find first-action.yml
        id: find-file
        run: |
          cd '../'
          ls -R
          find . -name first-action.yml
      #     echo "Finding first-action.yml"
      #     relative_path=$(find . -name first-action.yml)
      #     absolute_path=$(readlink -f "$relative_path")
      #     echo "Relative path: $relative_path"
      #     echo "Absolute path: $absolute_path"
      #     echo "::set-output name=relative_path::$relative_path"
      #     echo "::set-output name=absolute_path::$absolute_path"

      # - name: Output paths
      #   run: |
      #     echo "Relative path: ${{ steps.find-file.outputs.relative_path }}"
      #     echo "Absolute path: ${{ steps.find-file.outputs.absolute_path }}"



